name: Lint and Test Charts

on:
  pull_request:
    paths:
      - 'tests/charts/**'
      - '.github/workflows/pr.yml'

env:   
  KUBEVAL_VERSION: "0.16.0"
  KUBELINTER_VERSION: "0.4.0"

jobs:
  validate-chart:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        k8s:
          - v1.24.0
          - v1.23.6
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - id: kubeval
        uses: fox-md/helm-library/.github/compositeactions/kubeval@feature/add-v1.23.6
        with:
          version: "$KUBEVAL_VERSION"
      - id: kube-linter
        uses: fox-md/helm-library/.github/compositeactions/kube-linter@feature/add-v1.23.6
        with:
          version: "$KUBELINTER_VERSION"
      - name: Validate
        env:
          KUBERNETES_VERSION: ${{ matrix.k8s }}
        run: |
          CHART_DIRS="$(git diff --name-only origin/master origin/${GITHUB_HEAD_REF} | grep 'tests/charts' | egrep 'yaml|yml' | cut -d '/' -f3 | sort -u)"
          SCHEMA_LOCATION="https://raw.githubusercontent.com/instrumenta/kubernetes-json-schema/master/"

          echo "Validate charts"
          for CHART_DIR in ${CHART_DIRS}; do
            echo "Validating chart '${CHART_DIR}'"
            helm dependency update "tests/charts/${CHART_DIR}"
            helm lint "tests/charts/${CHART_DIR}"
            helm template "tests/charts/${CHART_DIR}" | kubeval --strict --ignore-missing-schemas --kubernetes-version "${KUBERNETES_VERSION#v}" --schema-location "${SCHEMA_LOCATION}"
            helm template "tests/charts/${CHART_DIR}" > all.yaml && kube-linter lint all.yaml
          done

  test-chart:
    name: install-chart
    runs-on: ubuntu-latest
    needs:
      - validate-chart
    strategy:
      matrix:
        k8s:
          - v1.24.0
          - v1.23.6
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Create kind ${{ matrix.k8s }} cluster
        uses: helm/kind-action@main
        with:
          node_image: kindest/node:${{ matrix.k8s }}
      - name: Deploy chart
        env:
          KUBERNETES_VERSION: ${{ matrix.k8s }}
        run: |
          kubectl config set-context kind-chart-testing

          echo "Deploy charts"
          CHART_DIRS="$(git diff --name-only origin/master origin/${GITHUB_HEAD_REF} | grep 'tests/charts' | egrep 'yaml|yml' | cut -d '/' -f3 | sort -u)"
          for CHART_DIR in ${CHART_DIRS}; do
            echo "Validating chart '${CHART_DIR}'"
            helm dependency update "tests/charts/${CHART_DIR}"
            helm install ${CHART_DIR} "tests/charts/${CHART_DIR}" --wait --timeout 90s --debug
            helm test ${CHART_DIR}
          done
